### ISSUE TITLE
Add max zoom option

### ISSUE THREAD

**Issue by awtur** [expenses/GAPDownloader#7]
Suggested improvements:
1. Add an argument to allow users to download the max zoom that doesn't exceed 65K (the jpg limit, I believe). 
2. If the users specifies a zoom level that exceeds the max, then automatically download the max zoom. (This is similar in purpose to 1)
3. If zoom is not specified, once the available levels are shown, ask users to input the level they want. 
4. If the URL is not provided, fetch it from the clipboard. For reference, see https://github.com/Boquete/google-arts-crawler/blob/master/crawler.py

**Comment by lovasoa** [comment]
The tool isn't tied to a particular image format, so I'm not sure about the JPEG-specific options. If someone wants a larger image, they can just save it in a different format.
I'm also not really in favor of reading the user's clipboard behind the scene. If the user wants to paste something, they can.

But adding an interactive mode seems to be a good idea ! It would make the tool more user-friendly. If the user launches the script without any parameter, it could interactively ask for an url, and then for a zoom level, instead of displaying an error as it currently does. A pull request implementing that would be welcome.

**Comment by awtur** [comment]
Thanks for considering these! There may have been a misunderstanding about my first suggestion: I was pointing out that anything above 65K can't be saved in JPG, so if there is a zoom level that exceeds that, then the program should go one level below that (I certainly don't have any interest in 65K or any lossless format that would result in unnecessarily huge file sizes).

Actually, suggestion #2 is at the top of my wishlist because I've come to realize that zoom 7 or 8 is very rarely preferable, so I tend ask for 5 or 6. My biggest frustration is that downloading is always a two step process: first find the zoom levels available, then specify the zoom you want. This is especially frustrating when downloading a list of items. If #2 is implemented, then the user could just specify the highest zoom they want (like 5), and if that level is NA, then the script would simply select the next highest. What do you think of this suggestion?

For the interactive features (asking for URL and size), have a look at the code for https://github.com/Boquete/google-arts-crawler/blob/master/crawler.py. My suggestion was based on that script.

**Comment by lovasoa** [comment]
Yes, you can open a pull request implementing falling back to the highest available zoom level, and interactive level selection. I'll be happy to review your code and merge it.

**Comment by awtur** [comment]
Unfortunately, I don't have programming experience, so as much as I would like to, I can't contribute. Perhaps we can leave these suggestions open until someone has the time/interest to look at them.
